database:
  mongo:
    url: mongodb://localhost:27017/2hang
    options:
      autoIndex: true
      useNewUrlParser: true
middlewares:
  cors:
    activate: true
    origin: '*'
    methods:
      - GET
      - POST
      - PUT
      - DELETE
routing:
port: 8001
